import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CarShopProvider, Product } from "@/context/CarShop/CarShopContext";
import { GetProducts } from "@/api/project/products";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="w-full h-screen bg-white px-10">
        <CarShopProvider>{children}</CarShopProvider>
      </body>
    </html>
  );
}
