import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CartShopProvider, Product } from '@/context/CartShop/CartShopContext';
import { GetProducts } from '@/api/project/products';
import Navbar from '@/components/organisms/Navbar';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='w-full bg-white px-0'>
        <CartShopProvider>
          <Navbar />
          {children}
        </CartShopProvider>
        <Toaster position='bottom-center' reverseOrder={false} />
      </body>
    </html>
  );
}
